// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVfALKmqGE751P1SvsQOEcdDgtuL0o3-c',
    appId: '1:1039308655412:web:0715c9d6b5bea31075f361',
    messagingSenderId: '1039308655412',
    projectId: 'coinone-gallery',
    authDomain: 'coinone-gallery.firebaseapp.com',
    storageBucket: 'coinone-gallery.appspot.com',
    measurementId: 'G-6BBZ5YCJ59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCudABIZoHEJkr3S9zTQ9vuYi2kTsk6ppA',
    appId: '1:1039308655412:android:b61e092abeec181375f361',
    messagingSenderId: '1039308655412',
    projectId: 'coinone-gallery',
    storageBucket: 'coinone-gallery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Hy4vdA2u7CaI7pYmYcuzRqPSx7N69fc',
    appId: '1:1039308655412:ios:e100883f87439f1a75f361',
    messagingSenderId: '1039308655412',
    projectId: 'coinone-gallery',
    storageBucket: 'coinone-gallery.appspot.com',
    iosBundleId: 'com.example.coinoneGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Hy4vdA2u7CaI7pYmYcuzRqPSx7N69fc',
    appId: '1:1039308655412:ios:e100883f87439f1a75f361',
    messagingSenderId: '1039308655412',
    projectId: 'coinone-gallery',
    storageBucket: 'coinone-gallery.appspot.com',
    iosBundleId: 'com.example.coinoneGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVfALKmqGE751P1SvsQOEcdDgtuL0o3-c',
    appId: '1:1039308655412:web:289ba7230163148375f361',
    messagingSenderId: '1039308655412',
    projectId: 'coinone-gallery',
    authDomain: 'coinone-gallery.firebaseapp.com',
    storageBucket: 'coinone-gallery.appspot.com',
    measurementId: 'G-Y74B0HQJJZ',
  );
}
